version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    image: my-abbatia:latest
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: abbatia
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'abbatia_inet'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'abd11TIA00'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5
# Names our volume
volumes:
  my-db:
